config/routes.rb
Socks::Application.routes.draw do
  resources :socks
  root 'socks#index'

  

end

app/models/sock.rb
class Sock < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/socks_controller.rb
class SocksController < ApplicationController
  before_action :set_sock, only: [:show, :edit, :update, :destroy]

  # GET /socks
  # GET /socks.json
  def index
    @socks = Sock.all
  end

  # GET /socks/1
  # GET /socks/1.json
  def show
  end

  # GET /socks/new
  def new
    @sock = Sock.new
  end

  # GET /socks/1/edit
  def edit
  end

  # POST /socks
  # POST /socks.json
  def create
    @sock = Sock.new(sock_params)

    respond_to do |format|
      if @sock.save
        format.html { redirect_to @sock, notice: 'Sock was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sock }
      else
        format.html { render action: 'new' }
        format.json { render json: @sock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /socks/1
  # PATCH/PUT /socks/1.json
  def update
    respond_to do |format|
      if @sock.update(sock_params)
        format.html { redirect_to @sock, notice: 'Sock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /socks/1
  # DELETE /socks/1.json
  def destroy
    @sock.destroy
    respond_to do |format|
      format.html { redirect_to socks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sock
      @sock = Sock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sock_params
      params.require(:sock).permit(:color, :foot, :size, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/socks_helper.rb
module SocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/socks/_form.html.erb
<%= form_for(@sock) do |f| %>
  <% if @sock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sock.errors.count, "error") %> prohibited this sock from being saved:</h2>

      <ul>
      <% @sock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :foot %><br>
    <%= f.text_field :foot %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/socks/edit.html.erb
<h1>Editing sock</h1>

<%= render 'form' %>

<%= link_to 'Show', @sock %> |
<%= link_to 'Back', socks_path %>

app/views/socks/index.html.erb
<h1>Listing socks</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Foot</th>
      <th>Size</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @socks.each do |sock| %>
      <tr>
        <td><%= sock.color %></td>
        <td><%= sock.foot %></td>
        <td><%= sock.size %></td>
        <td><%= sock.quantity %></td>
        <td><%= link_to 'Show', sock %></td>
        <td><%= link_to 'Edit', edit_sock_path(sock) %></td>
        <td><%= link_to 'Destroy', sock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sock', new_sock_path %>

app/views/socks/new.html.erb
<h1>New sock</h1>

<%= render 'form' %>

<%= link_to 'Back', socks_path %>

app/views/socks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @sock.color %>
</p>

<p>
  <strong>Foot:</strong>
  <%= @sock.foot %>
</p>

<p>
  <strong>Size:</strong>
  <%= @sock.size %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @sock.quantity %>
</p>

<%= link_to 'Edit', edit_sock_path(@sock) %> |
<%= link_to 'Back', socks_path %>